### ISSUE TITLE
--target is generated with incorrect value

### ISSUE THREAD

**Issue by tnozicka** [openshift/ci-operator-prowgen#16]
it generates `--target=[images]` but according to @smarterclayton (https://github.com/openshift/release/pull/1537#discussion_r218519398) it should be `--target=[release:latest]`

/kind bug
/cc @smarterclayton @stevekuznetsov

**Comment by smarterclayton** [comment]
For anything that is part of the openshift release (which excludes utilities and things that aren't on our branch cadence), it should currently be:

```
--target=[images]
--target=[release:latest]
```

**Comment by stevekuznetsov** [comment]
@smarterclayton so when you change the user-facing interface for this stuff, you should also change the generator and re-generate everything ...

**Comment by smarterclayton** [comment]
Only things using operators were testing it.  When you force prowgen, you
remove the ability to roll these things out slowly so as not to break
everyone all at once.

**Comment by tnozicka** [comment]
If it's not for all of them, there should be a flag on prowgen to use - we can't be supposed to edit generated files.

**Comment by stevekuznetsov** [comment]
"everything part of the openmshift release" is something `prowgen` already knows about -- it uses that to add your labels to the promotion jobs.

**Comment by smarterclayton** [comment]
Generally I prefer not to break everyone all at once.

Once everyone has their PR jobs for release verification, this won't be
necessary, because they will have a job template that depends on
RELEASE_IMAGE_LATEST and everything will work.

Until then, anyone part of the openshift release process has to have
[release:latest].  The slow rollout process is over anyway.

**Comment by stevekuznetsov** [comment]
Please find a way to fix the generator not to be broken. I want every single job generated -- templates or not -- within this sprint. We cannot have changes like this undermining that effort.

**Comment by petr-muller** [comment]
Hm can we close this one? I think we generate `--target=[release:latest]` in appropriate cases already.
