### ISSUE TITLE
Job name change is broken

### ISSUE THREAD

**Issue by tnozicka** [openshift/ci-operator-prowgen#41]
If I rename a job in CI operator yaml config and regenerate, it creates a new entry in prow config and leaves the old one there.

As the prow config should be generated it should update it. If I remove the file and regenerate I get the expected replace - should be by default though.

**Comment by stevekuznetsov** [comment]
No, this is expected behavior.

**Comment by stevekuznetsov** [comment]
Job names are the identifiers. It's not supported to change them. You can do it manually but we do not expect to support this case .

/close
